### ISSUE TITLE
WHU Building Result

### ISSUE THREAD

**Issue by LiuYustar** [stdcoutzrh/BuildingExtraction#1]
Hello blogger, I would like to ask if you have used this model to train and test on the WHU Building dataset, and if so, what is the result?

**Comment by stdcoutzrh** [comment]
Hello, the results of the model on the WHU test set are:
```shell
F1:95.90,
IOU:92.13,
OA:99.09,
Precision:96.23,
Recall:95.58.
```
Please note that this result is obtained by transfer learning using the parameters trained in the inria dataset.
Best wishes.
