### ISSUE TITLE
how can i  find sdscunet weights?

### ISSUE THREAD

**Issue by hanleju** [stdcoutzrh/BuildingExtraction#2]
i want to use "sdscunet-epoch105-bz8-0203" weights?
how can i find?
please help

**Comment by stdcoutzrh** [comment]
hello, can you give me your email, i will send it to you as soon as possible.

**Comment by hanleju** [comment]
dlgkswn3124@gmail.com
Thanks

**Comment by stdcoutzrh** [comment]
hello, I have sent the download link to your email. If you have any further questions, please continue to leave a message. Thank you.

**Comment by kikikikikinanana** [comment]
> hello, I have sent the download link to your email. If you have any further questions, please continue to leave a message. Thank you.

Hello. I want to receive weight file. My email is tester615243@gmail.com.
Please reply to me

**Comment by wwcc1107** [comment]
i want to use "0402-dsatnet-convnext-tiny" weights?
how can i find?
please help
my email is wangcgis@163.com
thank you!

**Comment by junhaoChang** [comment]
i want to use "0402-dsatnet-convnext-tiny" weights.
how can i find?

my email is [cjh9812@163.com](mailto:wangcgis@163.com)
Thank you very much！
