### ISSUE TITLE
你好，可以分享一下预训练权重吗？/mnt/sda/zrh/code/pretrained_ckpt/ckpt_T.pth

### ISSUE THREAD

**Issue by zhangronghuan** [stdcoutzrh/BuildingExtraction#5]
你好，可以分享一下预训练权重吗？/mnt/sda/zrh/code/pretrained_ckpt/ckpt_T.pth非常感谢！

**Comment by stdcoutzrh** [comment]
你好 可以从这里下载 https://drive.google.com/drive/folders/15iZKXFT7apjUSoN2WUMAbb0tvJgyh3YP

**Comment by fsqy-zhang** [comment]
你好，可以提供一个中文下载方式吗，比如百度网盘？

**Comment by stdcoutzrh** [comment]
> 你好，可以提供一个中文下载方式吗，比如百度网盘？

你好，链接在下面：
链接：https://pan.baidu.com/s/14daUSR_aj1L_UFfyfBDlHw?pwd=qwr7 
提取码：qwr7 
--来自百度网盘超级会员V6的分享

**Comment by lingliiii** [comment]
> 你好，可以分享一下预训练权重吗？/mnt/sda/zrh/code/pretrained_ckpt/ckpt_T.pth非常感谢！

请问您数据处理成功了吗？如果成功的话麻烦回复这个邮箱2001610101@mails.guet.edu.cn ，谢谢您！

**Comment by lingliiii** [comment]
> 你好，可以提供一个中文下载方式吗，比如百度网盘？

请问您复现成功了吗？如果成功的话麻烦回复这个邮箱2001610101@mails.guet.edu.cn ，谢谢您！
