### ISSUE TITLE
求mass数据集处理方法

### ISSUE THREAD

**Issue by Baccarali** [stdcoutzrh/BuildingExtraction#6]
您好，请问mass数据集的处理方法，是运行mass_patch_split.py文件吗？

**Comment by stdcoutzrh** [comment]
您好，先用[mass_patch_split.py]将图片处理成1500的图片，然后使用split_1500_to_512将图片处理成512x512的图片。

**Comment by lingliiii** [comment]
> 您好，请问mass数据集的处理方法，是运行mass_patch_split.py文件吗？

请问您数据处理成功了吗？如果成功的话麻烦回复这个邮箱2001610101@mails.guet.edu.cn ，谢谢您！
