### ISSUE TITLE
同问：Mass数据集的处理方法

### ISSUE THREAD

**Issue by zhangronghuan** [stdcoutzrh/BuildingExtraction#7]

**Comment by stdcoutzrh** [comment]
您好，先用[mass_patch_split.py]将图片处理成1500的图片，然后使用split_1500_to_512将图片处理成512x512的图片。

**Comment by Yuhang-Hong** [comment]
请问在使用mass_patch_split.py后，图片的格式改变了吗？

**Comment by lingliiii** [comment]
请问您数据处理成功了吗？如果成功的话麻烦回复这个邮箱2001610101@mails.guet.edu.cn ，谢谢您！

**Comment by stdcoutzrh** [comment]
> 请问在使用mass_patch_split.py后，图片的格式改变了吗？

mass数据集本身就是有tif和png两种格式的数据的，请从kaggle下载，下载下来就是tif和png都有。
https://www.kaggle.com/datasets/balraj98/massachusetts-buildings-dataset?resource=download
