### ISSUE TITLE
data processing 

### ISSUE THREAD

**Issue by Yuhang-Hong** [stdcoutzrh/BuildingExtraction#8]
请问作者的数据集是如何将tif格式的图片转换成png的呢，数据处理部分代码有些乱，还希望作者能够提示一下，便于复现，感谢。

**Comment by stdcoutzrh** [comment]
您好，请参考这里：https://github.com/stdcoutzrh/BuildingExtraction/issues/7

**Comment by stdcoutzrh** [comment]
> 请问作者的数据集是如何将tif格式的图片转换成png的呢，数据处理部分代码有些乱，还希望作者能够提示一下，便于复现，感谢。

mass数据集本身就是有tif和png两种格式的数据的，请从kaggle下载，下载下来就是tif和png都有。
https://www.kaggle.com/datasets/balraj98/massachusetts-buildings-dataset?resource=download
